spring:
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jrsaravanan/config-server-repo
          basedir: target/config

server:
  port: 8888
management:
context_path: /admin

info:
  component: Config Samples
endpoints:
  restart:
    enabled: true
logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG